"mkdir -p ~/.vim/autoload ~/.vim/bundle && \
"curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
"pip install flake8

syntax on
set nocompatible
filetype off
execute pathogen#infect()


autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif


" git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle
" required! 
Bundle 'gmarik/vundle'
" git clone https://github.com/vim-airline/vim-airline ~/.vim/bundle/vim-airline
Bundle 'bling/vim-airline'

" The bundles you install will be listed here
call vundle#end()
filetype plugin indent on

" let g:airline_symbols: 
let g:airline_powerline_fonts=1
let &t_Co=256
let g:airline#extensions#tabline#enabled = 1
let python_highlight_all = 1
set laststatus=2
set background=dark
set number
autocmd BufWritePost *.py call Flake8()
